### ISSUE TITLE
mcsmear crashes while returning status code 0

### ISSUE THREAD

**Issue by T-Britton** [JeffersonLab/halld_sim#36] opened 2019-01-18 15:23 UTC
a folder containing an example is at /osgpool/halld/tbritton/37030_0/

set your calib context to "variation=mc" and run the command in bold below.  You can see it produces a number of errors, writes 0 events and returns status code=0.

RUNNING MCSMEAR
running MCsmear without folding in random background
**mcsmear -PTHREAD_TIMEOUT=500 -o037030_000_geant3_smeared.hddm 037030_000_geant3.hddm**
JANA >> Enabling z compression of output HDDM file stream (default)
JANA >> Enabling CRC data integrity check in output HDDM file stream
JANA >>Opening source "037030_000_geant3.hddm" of type: HDDM
JANA >>Launching threads .
JANA >> THREAD_TIMEOUT_FIRST_EVENT is set smaller than THREAD_TIMEOUT
JANA >> (30 < 500). THREAD_TIMEOUT_FIRST_EVENT will be set to 500
JANA >>Installing special signal handler for mcsmear...
JANA >>Created JCalibration object of type: JCalibrationCCDB
JANA >>Generated via: JCalibration using CCDB for MySQL and SQLite databases
JANA >>Run:37030
JANA >>URL: sqlite:////group/halld/www/halldweb/html/dist/ccdb.sqlite
JANA >>context: variation=mc
JANA >>comment: 
JANA >>checking context = variation=mc
get BCAL/bcal_smear_parms_v2 parameters from CCDB...avg.: 0.0Hz)     
Get BCAL/digi_scales parameters from CCDB...0.0Hz  (avg.: 0.0Hz)     
Get BCAL/base_time_offset parameters from CCDB...  (avg.: 0.0Hz)     
JANA >>Creating DGeometry:1.0 events read)  0.0Hz  (avg.: 0.0Hz)     
JANA >>  Run requested:37030  found:37030
JANA >>  Run validity range: 37030-37030
JANA >>  URL="ccdb:///GEOMETRY/main_HDDS.xml"  context="default"
JANA >>  Type="JGeometryXML"
JANA >>Found 25 material maps in calib. DB
JANA >>Read in 25 material maps for run 37030 containing 76153 grid points total
Get FCAL/fcal_parms parameters from CCDB... 0.0Hz  (avg.: 0.0Hz)     
get FCAL/gains from calibDB
get FCAL/digi_scales parameters from calibDB0.0Hz  (avg.: 0.0Hz)     
get FCAL/mc_timing_smear parameters from calibDB
JANA >>get CDC/cdc_parms parameters from CCDB...z  (avg.: 0.0Hz)     
JANA >>get CDC/digi_scales parameters from CCDB... (avg.: 0.0Hz)     
Get FDC/fdc_parms parameters from CCDB...)  0.0Hz  (avg.: 0.0Hz)     
Get TOF/tof_parms parameters from CCDB...)  0.0Hz  (avg.: 0.0Hz)     
get TOF/paddle_resolutions from calibDB
Get START_COUNTER/start_parms parameters from CCDB...vg.: 0.0Hz)     
get START_COUNTER/paddle_mc_efficiency from calibDB
JANA ERROR>>RCDB: 'rtvs' condition is not set for run 37030.0Hz)     
JANA >> Factory Call Stack
JANA >>============================
JANA >> JEventLoop:OneEvent  (brun)  --   line:682  src/JANA/JEventLoop.cc
JANA >>----------------------------
src/JANA/JEventLoop.cc:685  EXCEPTION : map::at
src/JANA/JApplication.cc:1386  EXCEPTION caught for thread 139719610816256 : std::exception
JANA ERROR>> 
JANA ERROR>> Automatic relaunching of threads is disabled. If you wish to
JANA ERROR>> have the program relaunch a replacement thread when a stalled
JANA ERROR>> one is killed, set the JANA:MAX_RELAUNCH_THREADS configuration
JANA ERROR>> parameter to a value greater than zero. E.g.:
JANA ERROR>> 
JANA ERROR>>     jana -PJANA:MAX_RELAUNCH_THREADS=10
JANA ERROR>> 
JANA ERROR>> The program will quit now.
JANA >>
JANA >>Telling all threads to quit ...
JANA >>Merging thread 0 (0x7f1301c55700) ...

Closed HDDM file
 **0 event written to 037030_000_geant3_smeared.hddm
JANA >>Merging event reader thread ...
JANA >> 1 events processed  (11 events read) Average rate: 0.0Hz
return code is: 0**

**Comment by sdobbs** [comment] 2019-01-22 13:00
The return code bug is fixed in PR #35, while the cause of the crash (not checking the return value of the RCDB parsing function) had already been fixed in PR #30.

**Closed as completed by sdobbs** 2019-01-22 13:00 UTC
